### ISSUE TITLE
Compilation of electron ebuild fails with new version of dev-libs/icu

### ISSUE THREAD

**Issue by zaolin** [elprans/atom-overlay#11]
Hey,

compiling electron with the new version of dev-libs/icu-58.1 leads to:

error: #error "Update aspirational_scripts per Unicode 9.0"

Which can be fixed by an upgrade of the icu patch https://gitweb.gentoo.org/repo/gentoo.git/diff/www-client/chromium/files/chromium-icu-58.patch?id=c72212dd

BG Zaolin

**Comment by elprans** [comment]
Fixed.
