### ISSUE TITLE
electron-1.4.12 is out :)

### ISSUE THREAD

**Issue by orangecms** [elprans/atom-overlay#13]
I just tried building it by simply adjusting the version number for the ebuild and the patches. The official build ships with Node 6.5.0 and they are now using `browserify` during the build process, so I simply installed the latter through npm to some directory I have in my `$PATH`, but kept Node 6.3.0, as specified via the commit hash in the ebuild. I'll see what happens once compilation is done and try it with Node 6.5.0 as well. Would it make sense to add `npm` as a build dependency and add `npm install` and adjust the `$PATH` during the (e)merge?

Anyway, it's an awesome job you've done here! I've seen the TODOs in the ebuild, maybe I'll give them a shot :)

**Comment by elprans** [comment]
Unfortunately, updating Electron patches is a fairly laborious process. Chromium is a vast codebase, yet Electron takes that even further by integrating NodeJS into the mix. Electron ebuild updates are primarily motivated by the in-tree users, of which there is currently only one: Atom. Atom bumps its Electron dependency fairly infrequently, and it is likely that they will jump straight to electron-1.5, which has a major rework of the build system (gyp -> gn migration).

That said, I'll be happy to accept a working PR :-)

**Comment by orangecms** [comment]
Absolutely! The build almost went through, until it hit the headers of Atom and some other stuff, haha. I'll file a PR when I've made it! I just wish it would run a bit faster, haha. I was already amazed when the 1.3.x version finished. 🚀🙂

**Comment by elprans** [comment]
I use FEATURES="ccache" to make things faster.

**Comment by anthonyryan1** [comment]
+1 for this.

electron 1.3 and lower can no longer be built on systems with `>=net-print/cups-2.2.0`

Fix has been incorporated for 1.4

**Comment by elprans** [comment]
The cups fix will have to be backported to all versions currently in the tree.

**Comment by anthonyryan1** [comment]
If you're planning to backport the patch, you can find it here:

https://chromium.googlesource.com/chromium/src.git/+/29c1262dbd4f749dd514d05a571cdd809ba8cfe0%5E%21/#F0

**Comment by ghost** [comment]
Hello,

I've successfully built the [version 1.4.15](https://github.com/csmk/frabjous/blob/master/dev-util/electron/electron-1.4.15.ebuild), but that ebuild has some experimental stuff. Although I can clean up and do a PR. The only caveat is that I couldn't build without the system jinja.

Do you still have interest in this?

**Comment by orangecms** [comment]
Congratulations! I would absolutely want it, that would be awesome! I love experimental stuff, kudos :)

**Comment by elprans** [comment]
> I've successfully built the version 1.4.15, but that ebuild has some experimental stuff. Although I can clean up and do a PR. The only caveat is that I couldn't build without the system jinja.

The current 1.3 ebuild doesn't use system jinja anymore either.

> Do you still have interest in this?

Sure thing!

**Comment by ghost** [comment]
> The current 1.3 ebuild doesn't use system jinja anymore either.

I'm sorry, I think I didn't express myself correctly (language barrier, I'm still learning). I mean that if we remove the option to build with system jinja, the build will fail. To be honest, I didn't try harder to debug that part, because as we know, the stable 1.5 is around the corner.

> I would absolutely want it, that would be awesome!
> Sure thing!

Cool! I'll PR soon.
