### ISSUE TITLE
Electron-1.3.6 and electron-1.3.13 fail to build with cups USE flag enabled

### ISSUE THREAD

**Issue by brhenc** [elprans/atom-overlay#14]
We've been tracking the issue downstream from gentoo, I've rebuilt both electron-1.3.6 and electron-1.3.13 with and without the cups use flag. The build fails only when the cups use flag is enabled. Cups and cups-filters are both installed on the system as part of a normal gnome install.

Here's the link to our bugtracker:
https://bugs.funtoo.org/browse/FL-3511

Since the ebuild links against your fork of asar I presume you're the author of the ebuild, and I'd very much appreciate any advice on what causes the issue, and if it's a bug reproducible on a gentoo system.

I'd much rather work together on resolving the issue than rewriting the ebuild from scratch. Any pointer on where to start could save me hours of patching and recompiling.

There also *might* be issues when compiling with jinja >2.8, however, for reference here, jinja is kept at version 2.8.1. Both versions fail to build even with jinja-2.8.1 when the cups use flag is enabled.

**Comment by elprans** [comment]
I have a patch for that, will push later today as well as a PR for the gentoo tree.

**Comment by brhenc** [comment]
Thanks! I applied the patch referenced from the other issue https://chromium.googlesource.com/chromium/src.git/+/29c1262dbd4f749dd514d05a571cdd809ba8cfe0%5E%21/#F0 and it allows electron-1.3.13 to compile correctly.

**Comment by brhenc** [comment]
Also, switching to bundled jinja might be a good idea, it seems that versions >=2.9.0 cause the build to fail as well. 
https://gitweb.gentoo.org/repo/gentoo.git/commit/www-client/chromium?id=a57c78336e7c44f8d02f8591479953c181368b24

**Comment by elprans** [comment]
Fixed via #15
