### ISSUE TITLE
electron-1.4.15 fails to build with cups use flag or jinja>2.8

### ISSUE THREAD

**Issue by brhenc** [elprans/atom-overlay#18]
Just a friendly reminder that these issues still persist if not patched, you might
have a better way of solving this than using bundled ninja/including the cups 
header. 

Downstream issue at Funtoo: https://bugs.funtoo.org/browse/FL-3545
Basically duplicate of: https://github.com/elprans/atom-overlay/issues/14
Which was also tracked here: https://bugs.funtoo.org/browse/FL-3511

I can submit a pull request that uses those patches, however, you might have a
better solution. I'd like to inquire about the direction you're heading with the electron
ebuild, so that I can apply changes properly downstream (that keep things stable):

a) will you create a patch and modified ebuild every time jinja breaks the chromium build?
b) should jinja be slotted? 
c) will you use the bundled version of jinja instead? (like Gentoo did in https://bugs.gentoo.org/show_bug.cgi?id=605140)

I have no predilection for any of the solutions. Any one of them could potentially work. I'm only interested in keeping electron stable and changes compatible with Gentoo. It's not my call to decide here.

**Comment by elprans** [comment]
@csmk: do you mind sharing your build failures with bundled jinja?  As for the cups patch -- it was dropped accidentally in the merging of #16, I'll add it back.

As for jinja, newer chromium ebuilds seem to be using the bundled version, so that will likely be the way to go.

**Comment by brhenc** [comment]
Ok, thanks for the info!
Anyway, this is the bundled ninja ebuild + cups patch that worked for me in the last build I ran:
https://github.com/antematherian/atom-overlay/blob/master/dev-util/electron/electron-1.4.15-r1.ebuild
The diff is also available through a patch on https://bugs.funtoo.org/browse/FL-3545
Hope this is useful in some way.

**Comment by ghost** [comment]
> @csmk: do you mind sharing your build failures with bundled jinja?

Not at all. With the following change:

```diff
--- electron-1.4.15.ebuild
+++ electron-1.4.15-r1.ebuild
@@ -152,18 +152,14 @@
 	dev-python/beautifulsoup:python-2[${PYTHON_USEDEP}]
 	dev-python/beautifulsoup:4[${PYTHON_USEDEP}]
 	dev-python/html5lib[${PYTHON_USEDEP}]
-	dev-python/jinja[${PYTHON_USEDEP}]
 	dev-python/jsmin[${PYTHON_USEDEP}]
-	dev-python/ply[${PYTHON_USEDEP}]
 	dev-python/simplejson[${PYTHON_USEDEP}]
 ')"
 python_check_deps() {
 	has_version --host-root "dev-python/beautifulsoup:python-2[${PYTHON_USEDEP}]" &&
 	has_version --host-root ">=dev-python/beautifulsoup-4.3.2:4[${PYTHON_USEDEP}]" &&
 	has_version --host-root "dev-python/html5lib[${PYTHON_USEDEP}]" &&
-	has_version --host-root "dev-python/jinja[${PYTHON_USEDEP}]" &&
 	has_version --host-root "dev-python/jsmin[${PYTHON_USEDEP}]" &&
-	has_version --host-root "dev-python/ply[${PYTHON_USEDEP}]" &&
 	has_version --host-root "dev-python/simplejson[${PYTHON_USEDEP}]"
 }
 
@@ -296,7 +292,6 @@
 	# chromium patches
 	cd "${S}" || die
 	epatch "${FILESDIR}/chromium-system-ffmpeg-r2.patch"
-	epatch "${FILESDIR}/chromium-system-jinja-r11.patch"
 	epatch "${FILESDIR}/chromium-disable-widevine.patch"
 	epatch "${FILESDIR}/chromium-last-commit-position-r0.patch"
 	epatch "${FILESDIR}/chromium-remove-gardiner-mod-font-r0.patch"
@@ -377,6 +372,7 @@
 		'third_party/google_input_tools/third_party/closure_library/third_party/closure' \
 		'third_party/hunspell' \
 		'third_party/iccjpeg' \
+		'third_party/jinja2' \
 		'third_party/jstemplate' \
 		'third_party/khronos' \
 		'third_party/leveldatabase' \
@@ -397,6 +393,7 @@
 		'third_party/libyuv' \
 		'third_party/lss' \
 		'third_party/lzma_sdk' \
+		'third_party/markupsafe' \
 		'third_party/mesa' \
 		'third_party/modp_b64' \
 		'third_party/mt19937ar' \
@@ -415,6 +412,7 @@
 		'third_party/pdfium/third_party/libpng16' \
 		'third_party/pdfium/third_party/libtiff' \
 		'third_party/pdfium/third_party/zlib_v128' \
+		'third_party/ply' \
 		'third_party/polymer' \
 		'third_party/protobuf' \
 		'third_party/protobuf/third_party/six' \
```

I got this error:

```
 * PT_PAX marking -m out/R/nodebin with paxctl
 * XATTR_PAX marking -me out/R/nodebin with setfattr
ninja -v -j 5 -l 4 -C out/R electron
ninja: Entering directory `out/R'
ninja: warning: multiple rules generate chrome_200_percent.pak. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]
ninja: warning: multiple rules generate content_shell.pak. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]
ninja: warning: multiple rules generate natives_blob.bin. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]
ninja: warning: multiple rules generate snapshot_blob.bin. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]
ninja: error: '../../third_party/WebKit/Source/deps/jinja2/jinja2/__init__.py', needed by 'gen/blink/platform/v8_inspector/protocol/Console.cpp', missing and no known rule to make it
 * ERROR: dev-util/electron-1.4.15-r1::local failed (compile phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line 115:  Called src_compile
 *   environment, line 5088:  Called die
 * The specific snippet of code:
 *       eninja -C ${compile_target} ${ninja_targets} || die
```

I looked at the ebuild @antematherian mentioned above, and saw that he didn't removed the `chromium-system-jinja-r11.patch`. So I decided to add the patch back, then _voilà!_ It's all good now.

My initial thought was that the `chromium-system-jinja-r11.patch` was exclusively related to system's jinja. BTW, I don't have `dev-python/jinja` installed, so the bundled jinja was definitely used.

> As for the cups patch

It was [fixed in 1.4](https://github.com/elprans/atom-overlay/issues/13#issuecomment-271095336) isn't?

**Comment by brhenc** [comment]
Yes, the chromium-system-jinja-r11.patch is required when compiling with bundled jinja. I tried building without it first, but I got the same failure as you did @csmk.

**Comment by ghost** [comment]
chromium-system-jinja-r11.patch needed when compiling with system jinja, not bundled.

**Comment by brhenc** [comment]
chromium-system-jinja-r11 patch is not required with chromium 52 based electron. For some reason it fixes the build failure with chromium 53 and bundled jinja, which is highly unusual. Will try to see why if I find enough time. It definitely isn't from using system jinja, using system jinja even with the patch causes build failures. The build logs are at https://bugs.funtoo.org/browse/FL-3545 for jinja-2.9.4

**Comment by brhenc** [comment]
>[137/137]` x86_64-pc-linux-gnu-g++ -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -pthread -Wl,-z,noexecstack -fPIC -Wl,--disable-new-dtags -Wl,-rpath=\$ORIGIN/ -rdynamic -m64 -m64 -Wl,-O1 -Wl,--as-needed -Wl,--gc-sections -Wl,--no-as-needed -lpthread -Wl,--as-needed -Wl,--gc-sections -Wl,-rpath=\$ORIGIN/lib/ -Wl,-rpath-link=lib/ -o nodebin -Wl,--start-group obj/vendor/node/src/nodebin.node_main.o -Wl,--end-group lib/libnode.so -lz -lhttp_parser -lssl -lcrypto -licui18n -licuuc -licudata 
 \* PT_PAX marking -m out/R/nodebin with paxctl
 \* PT_PAX marking -m out/R/nodebin with scanelf
 \* XATTR_PAX marking -me out/R/nodebin with setfattr
ninja -v -j 23 -C out/R electron
ninja: Entering directory `out/R'
ninja: warning: multiple rules generate chrome_200_percent.pak. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]
ninja: warning: multiple rules generate content_shell.pak. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]
ninja: warning: multiple rules generate natives_blob.bin. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]
ninja: warning: multiple rules generate snapshot_blob.bin. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]
ninja: error: '../../third_party/WebKit/Source/deps/jinja2/jinja2/__init__.py', needed by 'gen/blink/platform/v8_inspector/protocol/Console.cpp', missing and no known rule to make it
 \* ERROR: dev-util/electron-1.4.15-r1::atom failed (compile phase):
 \*   (no error message)
 \* 
 \* Call stack:
 \*     ebuild.sh, line 115:  Called src_compile
 \*   environment, line 5077:  Called die
 \* The specific snippet of code:
 \*       eninja -C ${compile_target} ${ninja_targets} || die
 \* 
 \* If you need support, post the output of `emerge --info '=dev-util/electron-1.4.15-r1::atom'`,
 \* the complete build log and the output of `emerge -pqv '=dev-util/electron-1.4.15-r1::atom'`.
 \* 
 \* MemTotal:       50331648 kB
 \* SwapTotal:        262144 kB
 \* 
 \* The complete build log is located at '/var/tmp/portage/dev-util/electron-1.4.15-r1/temp/build.log'.
 \* The ebuild environment file is located at '/var/tmp/portage/dev-util/electron-1.4.15-r1/temp/environment'.
 \* Working directory: '/var/tmp/portage/dev-util/electron-1.4.15-r1/work/chromium-53.0.2785.143'
 \* S: '/var/tmp/portage/dev-util/electron-1.4.15-r1/work/chromium-53.0.2785.143'


Deinstalled system jinja and ran my ebuild without the patch (which uses bundled jinja). Sure enough, it causes a build failure that mirrors exactly what the system-jinja-r11 patch seems to fix:
https://github.com/elprans/atom-overlay/blob/master/dev-util/electron/files/chromium-system-jinja-r11.patch#L60-L69

Will try to break up patch into smaller chunks to see what's exactly needed. It should make it easier to see why the build failures happen.

**Comment by brhenc** [comment]
Ok the only part of the system-jinja-r11 patch that seems to be needed to compile correctly is this one:
https://github.com/antematherian/atom-overlay/blob/master/dev-util/electron/files/chromium-bundled-jinja-jinja.patch
>\--- third_party/WebKit/Source/platform/v8_inspector/v8_inspector.gyp.orig	2016-06-03 12:31:49.844954196 +0000
\+++ third_party/WebKit/Source/platform/v8_inspector/v8_inspector.gyp	2016-06-03 12:32:01.869198425 +0000
@@ -60,7 +60,6 @@
        {
           'action_name': 'generateV8InspectorProtocolBackendSources',
           'inputs': [
\-            '<@(jinja_module_files)',
             # The python script in action below.
             '../inspector_protocol/CodeGenerator.py',
\# Input files for the script.
Testing ebuild available here:
https://github.com/antematherian/atom-overlay/blob/master/dev-util/electron/electron-1.4.15-r2.ebuild

Jinja was uninstalled from the system while performing the build.

**Comment by ghost** [comment]
That's great! Thank you for dissecting the patch.

**Comment by ghost** [comment]
what's the stopper here?

**Comment by elprans** [comment]
I just pushed 1.4.15-r1 that builds for me with bundled jinja.  Please test.

**Comment by brhenc** [comment]
Thank you, I'll run a test and report back the result.

**Comment by brhenc** [comment]
Compiles correctly (with cups enabled, and jinja wasn't installed on the system, so it had to be bundled).
Thanks again for figuring out the issue.
