### ISSUE TITLE
electron-1.7.8-vendor-libchromiumcontent.patch needs to be updated

### ISSUE THREAD

**Issue by ghost** [elprans/atom-overlay#27]
There are many changes in [`libchromiumcontent/script/create-dist`](https://github.com/electron/libchromiumcontent/commit/3a083110f28ac441c92a5db82f9fb1dd51376039#diff-6bcdc4060f1a8322ee9b67ee3fcc7078).

Also, there's a new dependency on [ninja_syntax](https://pypi.python.org/pypi/ninja_syntax). At least, for that part I can help with this ebuild:

`dev-python/ninja_syntax/ninja_syntax-1.7.2.ebuild`

```ebuild
# Copyright 1999-2017 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

EAPI=6

PYTHON_COMPAT=( python2_7 python3_{4,5,6} pypy )

inherit distutils-r1

DESCRIPTION="Python module for generating .ninja files"
HOMEPAGE="https://github.com/ninja-build/ninja"
SRC_URI="mirror://pypi/${PN:0:1}/${PN}/${P}.tar.gz"

SLOT="0"
LICENSE="Apache-2.0"
KEYWORDS="amd64 x86 ~amd64-linux ~x86-linux"

DEPEND="dev-python/setuptools[${PYTHON_USEDEP}]"
```
But I'm not sure if it's worth adding another dependency just for that tiny part.

Cheers!

**Comment by elprans** [comment]
Fixed.
