### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by jonasstein** [elprans/atom-overlay#32]
Your overlay uses 
elprans  gmail com
see: https://gpo.zugaina.org/Overlays
as contact, but there is no bugzilla account with this mail address. 
There is a bugzilla account elvis magic io which is also connected to the proxy maintained packages.
We need a bugzilla account to assign bugs in your overlay to.

**Comment by elprans** [comment]
I opened https://github.com/gentoo/api-gentoo-org/pull/198 to sync the email address in the overlay metadata.
