### ISSUE TITLE
app-editors/vscode-1.30.0: `../src/node_sqlite3.cc:131:14: error: ‘SQLITE_LOCKED_VTAB’ was not declared in this scope`

### ISSUE THREAD

**Issue by lkraav** [elprans/atom-overlay#34]
`build.log` available at https://paste.pound-python.org/show/GMbpQymCl4ExRkTjM9h0/

**Comment by elprans** [comment]
Version of dev-db/sqlite?

**Comment by lkraav** [comment]
Ah yes, that's exactly what I forgot to ask from you, as well :)

```
$ qlist -IUv sqlite
dev-db/sqlite-3.23.1 (abi_x86_64 readline secure-delete)
```

**Comment by elprans** [comment]
Looks like you need at least 3.24.  I'll amend the DEPENDS
