### ISSUE TITLE
Electron 2.0.17 is not compatible with media-libs/libvpx-1.8.x

### ISSUE THREAD

**Issue by anthonyryan1** [elprans/atom-overlay#36]
Just noticed this today, I had keyworded >= 1.7.0 libvpx for electron and after it updated to 1.8.0 electron could no longer be built.

Because this issue traces back to the embedded chromium source code, and the issue has been fixed in Chromium, it'll probably be resolved in the next release that significantly updates the embedded chromium.

If interested i can send a PR to lock 2.0.17 to 1.7.0, otherwise this issue is mainly intended to track further developments on this.

**Comment by elprans** [comment]
It seems to be even worse with 3.x, which doesn't build with any system libvpx. FWIW, I added the `system-libvpx` USE flag to work around that.
