### ISSUE TITLE
Add vscodium editor

### ISSUE THREAD

**Issue by jorgicio** [elprans/atom-overlay#40]
Hi! I just noted that you have a recent version of Electron, as well as Atom and VScode editors.

Please, add VSCodium editor too. As well as I noted, the building way may be the same as vscode, but without the Microsoft addons.

Thanks in advice!

Greetings

**Comment by jachstet-sea** [comment]
If vscode is built from source by the ebuild (as it looks like but I haven't completely understood it yet), we automatically have the same result as "using" vscodium, right?
Or would you request to have the resulting binaries of the VSCodium project inside this overlay? Something like vscodium-bin?

**Comment by elprans** [comment]
AFAIK, vscodium is vscode with different branding and telemetry flag disabled by default.  I don't see good value there to justify the effort of maintaining it.
