### ISSUE TITLE
Please bump vscode to latest stable

### ISSUE THREAD

**Issue by Tatsh** [elprans/atom-overlay#42]
[1.36 release notes](https://code.visualstudio.com/updates/v1_36)

**Comment by jachstet-sea** [comment]
1.36.1 is out: https://github.com/Microsoft/vscode/milestone/99?closed=1

**Comment by PF4Public** [comment]
1.37 https://code.visualstudio.com/updates/v1_37

**Comment by Tatsh** [comment]
I looked into this a bit and one issue is Electron has to be updated to 4.2. The Electron ebuild is pretty far behind at 3.1.8.

**Comment by elprans** [comment]
They redid the build system in 4+ so this will (again) require a bunch of work.  I'm planning to skip 4 and 5 and jump straight to 6 or 7 depending on what vscode ends up using next.

**Comment by PF4Public** [comment]
By the look of their bugtracker, it seems that they are trying to get it working with electron 6

**Comment by elprans** [comment]
vscode-1.41 is in the tree.
