### ISSUE TITLE
vscode nodejs dependency issue

### ISSUE THREAD

**Issue by PF4Public** [elprans/atom-overlay#44]
vscode depends on nodejs like this:
>       >=net-libs/nodejs-6.11.0[${PYTHON_USEDEP}]

It worked fine until they replaced `python-single-r1` with `python-any-r1` in mainline nodejs ebuild.

electron dependency looks like this:
>      >=net-libs/nodejs-6.9.4

Please, remove `[${PYTHON_USEDEP}]` from vscode ebuild. I could do a PR if you'd like.

**Comment by elprans** [comment]
Latest vscode ebuild does not depend on nodejs anymore.
