### ISSUE TITLE
atom 1.10.0 ebuild?

### ISSUE THREAD

**Issue by soredake** [elprans/atom-overlay#5]

**Comment by elprans** [comment]
1.9 and 1.10 are blocked by electron 0.37 upgrade.  I have the ebuilds and patches, but the produced executables are faulty, see Gentoo bug [#583542](https://bugs.gentoo.org/show_bug.cgi?id=583542)  Any help debugging is welcome.

**Comment by elprans** [comment]
Electron issues have been resolved, and the 1.10 is now in the overlay.
