### ISSUE TITLE
dev-util/electron-6.1.6-r1 fails to compile getAllFieldPositions

### ISSUE THREAD

**Issue by mercuriete** [elprans/atom-overlay#52]
partial output:
```
error: ‘class icu::number::FormattedNumber’ has no member named ‘getAllFieldPositions’; did you mean ‘getAllFieldPositionsImpl’?
```
I think nodejs 14.2.0 is stable now and breaks electron.
https://packages.gentoo.org/packages/net-libs/nodejs

can somebody recompile electron today with all stable packages?

**Comment by 12101111** [comment]
You need https://github.com/gentoo/gentoo/blob/d2da708be8232c1fde4417584c056e519d015087/www-client/chromium/files/chromium-81-icu67.patch

**Comment by mercuriete** [comment]
thanks for the quick response.

can you do a re-release of dev-util/electron-6.1.6-r2 with that patch applied?

I will try to put it inside /etc/portage/patches/ in my machine.

**Comment by PF4Public** [comment]
dev-util/electron-6.1.6 also depends on `<dev-util/gn-0.1583`, while recent stable chromium requires `>=dev-util/gn-0.1726`, gn is however not slotted.

**Comment by mercuriete** [comment]
same problem than @PF4Public 
but I think that is another issue.
I am thinking on uninstalling vscode and install flatpak

**Comment by PF4Public** [comment]
> but I think that is another issue.

Sure, but I suppose, that bumping electron version would solve it without the need to opening a separate issue.

> I am thinking on uninstalling vscode and install flatpak

Lets see, what @elprans says in https://github.com/elprans/atom-overlay/issues/50#issuecomment-633257677

That issue also mentions another overlay. Could be a viable solution though.

**Comment by sandikata** [comment]
it fails to build even with such patch.

**Comment by lain3d** [comment]
fails for me as well with the patch.

**Comment by PF4Public** [comment]
I have attempted to write my version of [electron](https://github.com/PF4Public/gentoo-overlay/tree/master/dev-util/electron) and [vscode](https://github.com/PF4Public/gentoo-overlay/tree/master/app-editors/vscode) ebuilds based on the work of @elprans and @12101111.

Anyone interested may find them in my overlay [::pf4public](https://github.com/PF4Public/gentoo-overlay).

They both at the moment miss keywords  as they require some more work, but I could successfully compile them:
![Bildschirmfoto vom 2020-07-16 02-14-23](https://user-images.githubusercontent.com/10319700/87616595-0f6d7780-c71e-11ea-90b3-bb88b15313ea.png)

**Comment by elprans** [comment]
The current versions of electron in the overlay have been fixed.
