### ISSUE TITLE
This overlay is not for the atom editor

### ISSUE THREAD

**Issue by sspreitzer** [elprans/atom-overlay#53]
This overlay is listed as `atom` in https://overlays.gentoo.org, but it does not serve the atom editor.
Requesting for the removal of this overlay by the author from overlays.gentoo.org.

**Comment by elprans** [comment]
Fair enough.  I opened https://github.com/gentoo/api-gentoo-org/pull/336 to rename to electron-overlay.

**Comment by sspreitzer** [comment]
Thank you!
